import { getUuid } from '@/lib';
import { type IFolder } from '@/store';
import dayjs from 'dayjs';
const getT = (i: number) => {
  return dayjs(`2025-07-06 12:${i < 10 ? '0' + i : i}:00`)
    .valueOf()
    .toString();
};
export const data: IFolder[] = Array.from({ length: 60 }, (_, i) => ({
  id: getUuid(),
  name: '我的歌曲' + i,
  songCount: 1,
  createTime: getT(i),
  updateTime: getT(i),
  songs: [
    {
      id: getUuid(),
      name: '平凡之路',
      singer: '朴树',
      album: '平凡之路',
      duration: '04:15',
      createTime: getT(i),
      updateTime: getT(i),
      lyrics: [
        { content: '徘徊着的 在路上的' },
        { content: '你要走吗 via via' },
        { content: '易碎的骄傲着' },
        { content: '那也曾是我的模样' },
        { content: '沸腾着的 不安着的' },
        { content: '你要去哪儿 via via' },
        { content: '谜样的 沉着的' },
        { content: '故事你真的在听吗' },
        { content: '我曾经跨过山河大海' },
        { content: '也穿过人山人海' },
        { content: '我曾经拥有着的一切' },
        { content: '转眼都飘散如烟' },
        { content: '我曾经失落 失望' },
        { content: '失掉所有方向' },
        { content: '直到看见平凡才是唯一的答案' },
        { content: '当你仍然还在幻想' },
        { content: '你的明天 via via' },
        { content: '他会很暖还是很冷' },
        { content: '对我而言是另一天' },
        { content: '我曾经毁了我的一切' },
        { content: '只想永远地离开' },
        { content: '我曾经堕入雾的黑暗' },
        { content: '想挣扎无法自拔' },
        { content: '我曾经像你像他像那野草野花' },
        { content: '绝望着也渴望着' },
        { content: '也哭也笑平凡着' },
        { content: '我曾经跨过山河大海' },
        { content: '也穿过人山人海' },
        { content: '我曾经拥有着的一切' },
        { content: '转眼都飘散如烟' },
        { content: '我曾经失落 失望' },
        { content: '失掉所有方向' },
        { content: '直到看见平凡才是唯一的答案' },
        { content: '我曾经毁了我的一切' },
        { content: '只想永远地离开' },
        { content: '我曾经堕入雾的黑暗' },
        { content: '想挣扎无法自拔' },
        { content: '我曾经 像你 像他' },
        { content: '像那野草 野花' },
        { content: '绝望着也渴望着' },
        { content: '也哭也笑平凡着' },
        { content: '我曾经跨过山河大海' },
        { content: '也穿过人山人海' },
        { content: '我曾经问了整个世界' },
        { content: '从来没得到答案' },
        { content: '我不过像你 像他' },
        { content: '像那野草 野花' },
        { content: '冥冥中' },
        { content: '这是我唯一要走的路啊' },
        { content: '时间如烟 如此这般' },
        { content: '明天已在 yie yie' },
        { content: '风吹过的 如云烟' },
        { content: '你的故事讲到了哪儿' },
      ],
    },
  ],
}));
